/* Create Tables */
-- mfProdEco
CREATE TABLE [mfProdEco]
(
	-- ReturnType
	[ReturnType] varchar(4) NOT NULL,
	-- EcoSection
	[EcoSection] varchar(50),
	-- EcoFee
	[EcoFee] decimal(9,2),
	PRIMARY KEY ([ReturnType])
);

-- tblEncorp
CREATE TABLE [tblEncorp]
(
	-- ReturnType
	[ReturnType] varchar(4) NOT NULL,
	-- Code
	[Code] varchar(10),
	-- EncorpSectionKor
	[EncorpSectionKor] varchar(50),
	-- EncorpSection
	[EncorpSection] varchar(50),
	-- EncorpSize
	[EncorpSize] varchar(50),
	-- ConNumber
	[ConNumber] int,
	-- DepositValue
	[DepositValue] decimal(9,2),
	-- RecyclingFee
	[RecyclingFee] decimal(9,2),
	-- TotalFee
	[TotalFee] decimal(9,2),
	PRIMARY KEY ([ReturnType])
);

-- mfProd
CREATE TABLE mfProd (
	GalCode varchar(9) COLLATE Korean_Wansung_CI_AS NOT NULL,
	ProdOwnCode varchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SuppCode varchar(9) COLLATE Korean_Wansung_CI_AS NOT NULL,
	prodId nvarchar(15) COLLATE Korean_Wansung_CI_AS NULL,
	prodName nvarchar(60) COLLATE Korean_Wansung_CI_AS NULL,
	prodKname nvarchar(60) COLLATE Korean_Wansung_CI_AS NULL,
	prodType nvarchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	prodSupp nvarchar(4) COLLATE Korean_Wansung_CI_AS NULL,
	prodIUprice float NULL,
	prodOUprice float NULL,
	prodBal float NULL,
	prodBalw float NULL,
	prodProp float NULL,
	prodAisle nvarchar(12) COLLATE Korean_Wansung_CI_AS NULL,
	prodTax nvarchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	prodUnit nvarchar(4) COLLATE Korean_Wansung_CI_AS NULL,
	prodDeposit float NULL,
	prodPromo nvarchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	promoSdate smalldatetime NULL,
	promoEdate smalldatetime NULL,
	promoPrice float NULL,
	WeeklySaleYN bit NULL,
	LongTermSaleYN bit NULL,
	ManagerSaleYN bit NULL,
	BlowoutSaleYN bit NULL,
	prodImportBal float NULL,
	prodImportDate smalldatetime NULL,
	item nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	prodType2 nvarchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	prodWprice tinyint NULL,
	prodEdate smalldatetime NULL,
	prodlead int NULL,
	prodmorder int NULL,
	prodweight float NULL,
	prodsize nvarchar(30) COLLATE Korean_Wansung_CI_AS NULL,
	prodBalR float NULL,
	memberprice1 float NULL,
	memberprice2 float NULL,
	memberprice3 float NULL,
	memberprice4 float NULL,
	memberSdate smalldatetime NULL,
	memberEdate smalldatetime NULL,
	memberQty nchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	MemberLimitQty varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	PTStime nvarchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	PTEtime nvarchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	PTQty nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	PTPrice float NULL,
	dcYN varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	dc1Per int NULL,
	dc1TM varchar(5) COLLATE Korean_Wansung_CI_AS NULL,
	dc2Per int NULL,
	dc2TM varchar(5) COLLATE Korean_Wansung_CI_AS NULL,
	PIQty varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	PISDate smalldatetime NULL,
	PIEDate smalldatetime NULL,
	PIPrice float NULL,
	PIPoints int NULL,
	IsCP bit NULL,
	CPSDate smalldatetime NULL,
	CPEDate smalldatetime NULL,
	CPCpnQty varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	CPPrice float NULL,
	CPLimitQty varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	buyTime varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	CouponException varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	CouponExceptionSDate smalldatetime NULL,
	CouponExceptionEDate smalldatetime NULL,
	DCException varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	ManualPriceEntry varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	AutoReprint int NULL,
	IsDelivery bit NULL,
	AgeValidation bit NULL,
	CRMCoupon char(1) COLLATE Korean_Wansung_CI_AS NULL,
	SpecialCoupon char(1) COLLATE Korean_Wansung_CI_AS NULL,
	LastModPerson nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	LastModDate smalldatetime NULL,
	LastModTime nvarchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	useYN char(1) COLLATE Korean_Wansung_CI_AS NULL,
	webView char(1) COLLATE Korean_Wansung_CI_AS NULL,
	CONSTRAINT PK_mfProd PRIMARY KEY (GalCode,ProdOwnCode,SuppCode)
);

-- tblCustomer
CREATE TABLE tblCustomer (
	cardKey int NULL,
	CardNo char(12) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WebID varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	StoreCode char(1) COLLATE Korean_Wansung_CI_AS NULL,
	Lang_cd smallint NULL,
	CustLanguage varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
	Sex char(1) COLLATE Korean_Wansung_CI_AS NULL,
	EnName varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
	Phone varchar(15) COLLATE Korean_Wansung_CI_AS NULL,
	Phone_1 varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	Address varchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	city_cd smallint NULL,
	City varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
	province_cd smallint NULL,
	Province varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	country_cd smallint NULL,
	PostalCode varchar(6) COLLATE Korean_Wansung_CI_AS NULL,
	EMail varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	email_host varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	exchange_server_nm varchar(70) COLLATE Korean_Wansung_CI_AS NULL,
	BirthYear smallint NULL,
	BirthDate smalldatetime NULL,
	BirthDateHistDec312008 smalldatetime NULL,
	Family int NULL,
	family_cnt smallint NULL,
	KrName varchar(40) COLLATE Korean_Wansung_CI_AS NULL,
	Anniversary smalldatetime NULL,
	AppDate smalldatetime NULL,
	CardIssueDate smalldatetime NULL,
	CardIssueTime varchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	CardIssueStore char(1) COLLATE Korean_Wansung_CI_AS NULL,
	CardIssuePassWord varchar(12) COLLATE Korean_Wansung_CI_AS NULL,
	CardIssuePerson varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	RefCardNo char(12) COLLATE Korean_Wansung_CI_AS NULL,
	OldCardNo char(12) COLLATE Korean_Wansung_CI_AS NULL,
	Active bit NULL,
	InactiveReason varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	ActiveModDate smalldatetime NULL,
	ActiveModTime varchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	ActiveModStore char(1) COLLATE Korean_Wansung_CI_AS NULL,
	ActiveModPassWord varchar(12) COLLATE Korean_Wansung_CI_AS NULL,
	ActiveModPerson varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	Terminated bit NULL,
	TerminateDate smalldatetime NULL,
	TerminateTime varchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	TerminateStore char(1) COLLATE Korean_Wansung_CI_AS NULL,
	TerminatePassWord varchar(12) COLLATE Korean_Wansung_CI_AS NULL,
	TerminatePerson varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	NewCardNo char(12) COLLATE Korean_Wansung_CI_AS NULL,
	LastModDate smalldatetime NULL,
	LastModTime varchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	LastModStore char(1) COLLATE Korean_Wansung_CI_AS NULL,
	LastModPassWord varchar(12) COLLATE Korean_Wansung_CI_AS NULL,
	LastModPerson varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	LastTranDate smalldatetime NULL,
	LastTranTime varchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	LastTranStore char(1) COLLATE Korean_Wansung_CI_AS NULL,
	LastTranPassWord varchar(12) COLLATE Korean_Wansung_CI_AS NULL,
	LastTranPassStation varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	LastTranInvNo int NULL,
	LastTranRInvNo int NULL,
	LastTranPoint int NULL,
	EstCancelledPoint int NULL,
	EstCancelledDate smalldatetime NULL,
	CancelledPoint int NULL,
	LastPointChangeDate smalldatetime NULL,
	PointCancelDate smalldatetime NULL,
	CollectedPoint int NULL,
	agree char(1) COLLATE Korean_Wansung_CI_AS NULL,
	sync_ck smallint NOT NULL,
	sync_dt datetime NOT NULL,
	ip_company smallint NULL,
	ip_id smallint NULL,
	ip_dt datetime NULL,
	CONSTRAINT PK_tblCustomer PRIMARY KEY (CardNo)
);
-- tblCustomerHist
CREATE TABLE tblCustomerHist (
	HistID int IDENTITY(1,1) NOT NULL,
	CardNo char(12) COLLATE Korean_Wansung_CI_AS NULL,
	Renewed bit NULL,
	Inactivated bit NULL,
	Activated bit NULL,
	Terminated bit NULL,
	InactiveReason varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	OldCardNo char(12) COLLATE Korean_Wansung_CI_AS NULL,
	NewCardNo char(12) COLLATE Korean_Wansung_CI_AS NULL,
	HistDate smalldatetime NULL,
	HistTime varchar(16) COLLATE Korean_Wansung_CI_AS NULL,
	HistStore char(1) COLLATE Korean_Wansung_CI_AS NULL,
	HistPassWord varchar(12) COLLATE Korean_Wansung_CI_AS NULL,
	HistPerson varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	Sync bit NULL,
	CONSTRAINT PK_tblCustomerHist PRIMARY KEY (HistID)
);

