spring:
  profiles:
    active: local

## MULTIPART (MultipartProperties)
# 1.Enable multipart uploads
# 2.Threshold after which files are written to disk.
# 3.Max file size.
# 4.Max Request Size
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: ./uploads

#받기로 한 값 이외는 에러
#spring.jackson.deserialization.fail-on-unknown-properties=true
my-app:
  test-username: dev9000@gmail.com
  test-password: 1234
  client-id: HNS-SHOP
  client-secret: pass

    
--- #local 환경
spring:
  profiles: local
  
  hnsshop:
    datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://192.168.99.100:1433;databaseName=hnsshop
      username: sa
      password: Pa33word
  srypos:
    datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://192.168.99.100:1433;databaseName=wholesaleDB
      username: sa
      password: Pa33word

#Server HTTP port
server:
  port: 8081

#Server AJP port
tomcat:
  ajp-enabled: true
  ajp-protocol: AJP/1.3
  ajp-port: 18009
  
logging:
  file:
    path: C:/Hannam/hns-shop-sry/logs
  level:
    root: info

--- #test 환경
spring:
  profiles: test
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: westViewM001@gmail.com
    password: wvIt2019!
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
  
  hnsshop:
    datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://172.16.3.60:1433;databaseName=hnsshop
      username: shopdev
      password: WVit#2020
  srypos:
    datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://172.16.1.29:1433;databaseName=wholesaleDB
      username: wssale
      password: w2015

#Server HTTP port
server:
  port: 8081

#Server AJP port
tomcat:
  ajp-enabled: true
  ajp-protocol: AJP/1.3
  ajp-port: 18009

logging:
  file:
    path: C:/Hannam/hns-shop-sry/logs
  level:
    root: info

--- #real 환경
spring:
  profiles: real

  hnsshop:
    datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://172.16.3.60:1433;databaseName=hnsshop
      username: shopdev
      password: WVit#2020
  srypos:
    datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://172.16.1.29:1433;databaseName=wholesaleDB
      username: wssale
      password: w2015

#Server HTTP port
server:
  port: 8081

#Server AJP port
tomcat:
  ajp-enabled: true
  ajp-protocol: AJP/1.3
  ajp-port: 18009
  
logging:
  file:
    path: C:/Hannam/hns-shop-sry/logs
  level:
    root: info
